import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "./index.module.scss";
import Header from "../components/header/Header";
import Main from "../components/main/Main";
import Characters from "../components/characters/Characters";
import Layout from "../layouts/Layout";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Rick and Morty - App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.HomePage}>
        <Layout>
          <Characters />
        </Layout>
      </div>
    </>
  );
};

export default Home;
